//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffEasy.AppFiles.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Archive
    {
        public int Number { get; set; }
        public string DocName { get; set; }
        public Nullable<int> IdTypeDoc { get; set; }
        public Nullable<bool> DocStatus { get; set; }
        public Nullable<bool> ConfOfLoss { get; set; }
        public Nullable<bool> ConfOfTrade { get; set; }
        public Nullable<bool> ConfOfDestroy { get; set; }
        public Nullable<int> IdEduLevel { get; set; }
        public string DocSeries { get; set; }
        public string DocNumber { get; set; }
        public Nullable<System.DateTime> DateOfIssue { get; set; }
        public string RegNumber { get; set; }
        public Nullable<int> SpecializationCode { get; set; }
        public string SpecializationName { get; set; }
        public string NameOfQual { get; set; }
        public string NameEduProg { get; set; }
        public Nullable<int> YearOfAdmission { get; set; }
        public Nullable<int> YearOfEnd { get; set; }
        public Nullable<int> EduDuration { get; set; }
        public string SurnameOfRecepient { get; set; }
        public string NameOfRecepient { get; set; }
        public string MiddleNameOfRecepinet { get; set; }
        public Nullable<System.DateTime> DOBRecepinet { get; set; }
        public Nullable<bool> SexRecepinet { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<int> EduForm { get; set; }
        public Nullable<int> FormOfEducationTermination { get; set; }
        public Nullable<int> SourceOfFinancing { get; set; }
        public Nullable<bool> AvailabilityOfСontract { get; set; }
    
        public virtual CountryCode CountryCode1 { get; set; }
        public virtual DocType DocType { get; set; }
        public virtual EducationForm EducationForm { get; set; }
        public virtual EducationLevel EducationLevel { get; set; }
        public virtual FormOfEducationTermination FormOfEducationTermination1 { get; set; }
        public virtual SourceOfFinancing SourceOfFinancing1 { get; set; }
        public virtual SpecializationCode SpecializationCode1 { get; set; }
    }
}
