//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StaffEasy.AppFiles.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedicalRecords
    {
        public int MedicalRecordID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string MedicalInfo { get; set; }
    
        public virtual Employees Employees { get; set; }
    }
}
